version: "3.4"

services:

  django:
    container_name: django
    image: django
    restart: always
    env_file: env
    networks:
      - traefik
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=Host(`example.com`,`www.example.com`)
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.tls.certresolver=le
      - traefik.http.services.example.loadbalancer.server.port=8000
      - traefik.enable=true

  worker_email:
    image: django
    command: ./manage.py send_email_worker
    restart: always
    env_file: env
    networks:
      - db

# Enable this worker if you want to enable the SMS worker
#  worker_sms:
#    image: django
#    command: ./manage.py send_sms_worker
#    restart: always
#    env_file: env
#    networks:
#      - db

# Enable this worker if you want to push the healthcheck
#  worker_healthcheck_push:
#    image: django
#    command: ./manage.py healthcheck_push
#    restart: always
#    env_file: env
#    networks:
#      - db


networks:
  traefik:
    external: true
  db:
    external: true
