version: "2.4"

services:

  django:
    container_name: django
    image: django
    restart: always
    env_file: env
    networks:
      - traefik
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=Host(`example.com`,`www.example.com`)
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.tls.certresolver=le
      - traefik.http.services.example.loadbalancer.server.port=8000

      # Redirect non-www to www middleware
      - traefik.http.middlewares.example-nonwww.redirectregex.regex=^https://example.com/(.*)
      - traefik.http.middlewares.example-nonwww.redirectregex.replacement=https://www.example.com/$${1}
      - traefik.http.middlewares.example-nonwww.redirectregex.permanent=true

      # Adjust these as needed
      - "traefik.http.middlewares.example-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.example-ratelimit.ratelimit.burst=20"

      - traefik.http.routers.example.middlewares=example-nonwww@docker,gzip@docker,example-ratelimit@docker

  worker_email:
    image: django
    command: ./manage.py send_email_worker
    restart: always
    env_file: env
    networks:
      - db

# Enable this worker if you want to enable the SMS worker
#  worker_sms:
#    image: django
#    command: ./manage.py send_sms_worker
#    restart: always
#    env_file: env
#    networks:
#      - db

# Enable this worker if you want to push the healthcheck
#  worker_healthcheck_push:
#    image: django
#    command: ./manage.py healthcheck_push
#    restart: always
#    env_file: env
#    networks:
#      - db


networks:
  traefik:
    external: true
  db:
    external: true
