version: "3.4"

services:

  django:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    env_file: env
    depends_on:
        - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        # this matches the values in the env.sample file
        POSTGRES_DB: django_reference
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass123

  # if in development
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    restart: always
    volumes:
        - mailpit_data:/data
    ports:
        - "8025:8025"
        - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  simple_async_worker:
    build:
        context: .
        dockerfile: Dockerfile
    command: ./manage.py simple_async_worker
    restart: always
    env_file: env
    depends_on:
        - postgres
